root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main cmd/web/main.go"
delay = 1000
exclude_dir = ["assets", "tmp", "vendor"]
exclude_file = []
exclude_regex = [".*_templ.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = "ENV=development ./tmp/main"
include_dir = ["cmd/web"]
include_ext = ["go", "hbs"]
kill_delay = "2s"
log = "build-errors.log"
send_interrupt = true
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
time = false

[misc]
clean_on_exit = false
